services:
  # Web service for the Streamlit app
  - type: web
    name: distillnet-app
    runtime: docker
    image: docker.io/${DOCKER_USERNAME}/distillnet-streamlit:latest
    region: oregon
    plan: free
    envVars:
      - key: DOCKER_USERNAME
        sync: false
      - key: PORT
        value: 8501
    healthCheckPath: /
    autoDeploy: false

  # Background worker for training (optional)
  - type: worker
    name: distillnet-training
    env: docker
    plan: free
    image:
      url: ${DOCKER_USERNAME}/distillnet-training:latest
    envVars:
      - key: DOCKER_USERNAME
        sync: false
    buildCommand: python src/train_student.py 