services:
  # Web service for the Streamlit app
  - type: web
    name: distillnet-streamlit
    env: docker
    plan: free
    dockerCommand: streamlit run app/streamlit_app.py
    image:
      url: ${DOCKER_USERNAME}/distillnet-streamlit:latest
    envVars:
      - key: DOCKER_USERNAME
        sync: false
    healthCheckPath: /
    autoDeploy: true

  # Background worker for training (optional)
  - type: worker
    name: distillnet-training
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.training
    dockerContext: .
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
    command: python src/train_student.py 