services:
  # Web service for the Streamlit app
  - type: web
    name: distillnet-streamlit
    env: docker
    plan: free
    image:
      url: ${DOCKER_USERNAME}/distillnet-streamlit:latest
    envVars:
      - key: DOCKER_USERNAME
        sync: false
    healthCheckPath: /
    autoDeploy: true

  # Background worker for training (optional)
  - type: worker
    name: distillnet-training
    env: docker
    plan: free
    image:
      url: ${DOCKER_USERNAME}/distillnet-training:latest
    envVars:
      - key: DOCKER_USERNAME
        sync: false
    buildCommand: python src/train_student.py 