name: Build & Push Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Streamlit app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.streamlit
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/distillnet-streamlit:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/distillnet-streamlit:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/distillnet-streamlit:buildcache,mode=max
          
      # Temporarily commented out until Render deploy hook is available
      # - name: Trigger Render Deployment
      #   run: |
      #     curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
      #   if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') 