name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Streamlit app
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.streamlit
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/distillnet-streamlit:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/distillnet-streamlit:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/distillnet-streamlit:buildcache,mode=max
          
      - name: Build and push Training image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.training
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/distillnet-training:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/distillnet-training:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/distillnet-training:buildcache,mode=max 