name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Create minimal Dockerfile
        run: |
          echo "Creating minimal Dockerfile..."
          cat > Dockerfile.minimal << 'EOL'
FROM python:3.9-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir streamlit

# Create a simple Streamlit app
RUN mkdir -p /app/app
RUN echo 'import streamlit as st\n\nst.set_page_config(page_title="DistillNet", layout="wide")\n\nst.title("DistillNet Image Classifier")\n\nst.write("This is a minimal version of the app for testing deployment.")\n\nst.success("Deployment successful!")' > /app/app/app.py

# Set environment variables
ENV PYTHONPATH=/app
ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0

# Expose port for Streamlit
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "/app/app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
EOL
          
          echo "Contents of Dockerfile.minimal:"
          cat Dockerfile.minimal
      
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t distillnet:minimal -f Dockerfile.minimal .
      
      - name: Test Docker image
        run: |
          echo "Running Docker container for testing..."
          docker run -d --name distillnet-test -p 8501:8501 distillnet:minimal
          
          echo "Waiting for container to start..."
          sleep 10
          
          echo "Container logs:"
          docker logs distillnet-test
          
          echo "Stopping container..."
          docker stop distillnet-test
          
          echo "Docker image built and tested successfully!" 